ci:
  collect:
    settings:
      disableStorageReset: true
      maxWaitForLoad: 90000
      throttlingMethod: devtools
      additive: false
  assert:
    present: lighthouse:recommended
    assertMatrix:
      - matchingUrlPattern: .*(--pr|localhost).*
        assertions:
          categories:performance:
            - error
            - minScore: 0.7
          categories:accessibility:
            - error
            - minScore: 0.7
          categories:best-practices:
            - error
            - minScore: 1
          categories:seo:
            - error
            - minScore: 0.8
          categories:pwa: 'off'
  upload:
    target: temporary-public-storage
