---
branches:
  - '+([0-9])?(.{+([0-9]),x}).x'
  - name: main
    channel: stable
  - name: next
    prerelease: beta
    channel: canary
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/npm'
  - '@semantic-release/changelog'
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
      # https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci
      message: |-
        chore(release): ${nextRelease.version} [skip ci]
        ${nextRelease.notes}
  - '@semantic-release/github'
